name: Tests

on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.7'
    - name: Set permissions
      run : |
        sudo chmod 777 ./test.py
    - name: Unit Tests
      run: |
        ./test.sh >> output.txt && ./test.py
