name: Tests

on: [push]

jobs:
  build:
    name: Tests
    strategy:
      matrix: 
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Go
      run:  |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang
    - name: Set permissions
      run : |
        sudo chmod 777 ./test.py
    - name: Unit Tests
      with:
        go-version: ${{ matrix.go }}
      run: |
        ./test.sh > output.txt &&
        ./test.py