name: Tests

on: [push]

jobs:
  unit:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Go
      run:  |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang
    - name: Set permissions
      run : |
        sudo chmod 777 ./test.sh
    - name: Unit Tests
      run: |
        (./test.sh > output.txt &)
        ./test.py